export const FETCH_POKEMONS_SUCCESS = 'FETCH_POKEMONS_SUCCESS';
export const FETCH_POKEMONS_FAILURE = 'FETCH_POKEMONS_FAILURE';
export const SORT_POKEMONS_FAILURE = 'SORT_POKEMONS_FAILURE';
export const SORT_POKEMONS_SUCCESS = 'SORT_POKEMONS_SUCCESS';

export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';